#!/bin/sh


if [ $2 ]
then
    pdffile=${2%.*}
    ./JumanG.py $* && pdflatex $2 && evince $pdffile.pdf
elif [ $1 ]
then
    outputFile="result.out"
    pdffile=${outputFile%.*}
    ./JumanG.py $* $outputFile && pdflatex $outputFile && evince $pdffile.pdf
else
    ./JumanG.py $*
fi
